from . import product_template
from . import product_product
from . import qurbani_day
from . import hijri
from . import chand_raat
from . import city_schedule
from . import slaughter_schedule
from . import distribution_schedule
from . import qurbani_order
from . import qurbani_order_line
from . import pos_config
from . import qurbani_city_demand
from . import qurbani_slaughter_demand
from . import qurbani_slaughter_slot_demand
from . import res_company
from . import pos_session
from . import qurbani_cow_slaughter
from . import qurbani_goat_slaughter
from . import pos_order