{
    'name': 'Livestock Slaugther',
    'version': '1.0',
    'author': 'Syed Owais Noor',
    'website': 'http://bytesnode.com',
    'license': 'LGPL-3',
    'category': 'BytesNode/Livestock Slaugther',
    'depends': [
        'bn_donation_home_service',
        'mail',
    ],
    'data': [
        'data/sequence.xml',
        'data/stock_location.xml',
        'security/ir.model.access.csv',
        'views/livestock_slaugther.xml',
        'views/livestock_requisition.xml',
        'views/livestock_cutting.xml',
        'views/livestock_cutting_material.xml',
        'views/product_packaging.xml',
        'views/package_type.xml',
        'views/meat_management.xml',
        'views/distribution_center.xml',
        'wizards/livestock_slaugther.xml',
    ],
    'auto_install': False,
    'application': True,
}