{
    'name': 'Qurbani',
    'version': '1.0',
    'author': 'Syed Owais Noor',
    'website': 'http://bytesnode.com',
    'license': 'LGPL-3',
    'category': 'BytesNode/Qurbani',
    'depends': [
        'bn_stock_location',
        'bn_donation_home_service',
        'bn_pos_customization',
        'bn_pos_payment_method',
        'bn_res_company',
        'bn_pos_order',
    ],
    'data': [
        'data/sequence.xml',
        'data/chand_raat.xml',
        'data/qurbani_day.xml',
        'security/group.xml',
        'security/ir.model.access.csv',
        'views/product_template.xml',
        'views/product_product.xml',
        'views/qurbani_day.xml',
        'views/hijri.xml',
        'views/chand_raat.xml',
        'views/city_schedule.xml',
        'views/slaughter_schedule.xml',
        'views/distribution_schedule.xml',
        'views/qurbani_order.xml',
        'views/pos_config.xml',
        'views/qurbani_city_demand.xml',
        'views/qurbani_slaughter_demand.xml',
        'views/qurbani_slaughter_slot_demand.xml',
        'views/res_company.xml',
        'wizards/qurbani_schedule.xml',
        'wizards/generate_qurbani_demand.xml',
        'reports/qurbani_token.xml',
    ],
    'auto_install': False,
    'application': True,
    'assets': {
        'point_of_sale._assets_pos': [
            'bn_qurbani/static/src/app/**/*',
            'bn_qurbani/static/src/screens/**/*',
            'bn_qurbani/static/src/components/**/*',
            'bn_qurbani/static/src/models/**/*',
        ],
    }
}