from . import pos_order
from . import pos_payment_method
from . import pos_session
from . import res_company
from . import res_config_setting
from . import pos_session_slip
from . import pos_config
from . import account_journal
from . import account_move_line