{
    "name": "Custom Point Of Sale Apps",
    "summary": """
       Custom Point Of Sale Apps
    """,
    "description": """
        Custom Point Of Sale Apps
    """,
    "category": "TechnoCoderSol/PointOfSaleApps",
    "author": "Shariq Ali Mehdi",
    "version": "17.0",
    'license': 'OPL-1',
    # 'depends': ['base', 'stock', 'point_of_sale', 'account', 'base_accounting_kit', 'hr_expense', 'c2p_profile_management', 'advanced_pos_reports', 'pos_sale', 'pos_customer_feedback'],
    'depends': ['base', 'mail', 'hr_expense', 'advanced_pos_reports', 'pos_sale', 'pos_customer_feedback', 'pos_microfinance_loan', 'bn_pos_qr_code', 'sm_donation_box', 'bn_import_donation'],
    "data": [
        'security/ir.model.access.csv',
        'security/head_of_department_res_group.xml',
        'data/account_account_data.xml',
        'data/account_journal_data.xml',
        'data/account_config_settings_data.xml',
        'data/amount_type_data.xml',
        'data/amount_currency_box_sequence_data.xml',
        'data/amount_currency_box_lines_sequence_data.xml',
        'data/amount_currency_fake_notes_sequence_data.xml',
        'data/amount_currency_deposit_sequence_data.xml',
        'data/product_stock_move_sequence_data.xml',
        'data/product_stock_move_lines_sequence_data.xml',
        'data/product_valuation_lines_sequence_data.xml',
        'data/donation_by_home_service_sequence_data.xml',
        'data/product_stock_move_config_data.xml',
        # 'data/res_partner_sequence_data.xml',
        'menus/account_menu.xml',
        'menus/stock_menu.xml',
        'views/account_config_setting_view.xml',
        'views/amount_type_view.xml',
        'views/amount_currency_box_view.xml',
        'views/amount_currency_box_lines_view.xml',
        'views/amount_currency_deposit_view.xml',
        'views/product_stock_move_config_view.xml',
        'views/product_stock_move_view.xml',
        'views/product_stock_move_lines_view.xml',
        'views/donation_by_home_service_view.xml',
        'views/pos_category_view.xml',
        # 'views/res_partner_view.xml',
        'views/product_template_view.xml',
        'views/pos_payment_method_view.xml',
        'views/res_partner.xml',
        'DonationBoxSlip/template.xml',
        'DonationHomeServiceSlip/template.xml',
        'MedicalEqSlip/template.xml',
        'wizard/amount_currency_wizard.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'sm_point_of_sale_apps/static/src/xml/**/*.xml',
            'sm_point_of_sale_apps/static/src/js/**/*.js',
        ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
}
