from . import donation_box_request
from . import donation_box_request_line
from . import donation_box_registration_intallation
from . import donation_box_complain_center
from . import stock_lot
from . import product_product
from . import res_partner
from . import product_template
from . import stock_move