from . import res_partner
from . import microfinance
from . import microfinance_line
from . import microfinance_recovery_line
from . import microfinance_education
from . import microfinance_guarantor
from . import microfinance_family
from . import microfinance_installment
from . import product_product
from . import product_template
from . import loan_product_line