{
    'name': 'Shariah Law',
    'version': '1.0',
    'author': 'Syed Owais Noor',
    'website': 'https://bytesnode.com/',
    'license': 'LGPL-3',
    'category': 'BytesNode/Shariah Law',
    'depends': [
        'bn_analytic_account_customization',
        'bn_import_donation',
        'purchase',
        'hr_expense',
        'point_of_sale',
    ],
    'data': [
        'data/schedule_action.xml',
        'data/sequence.xml',
        'security/group.xml',
        'security/ir.model.access.csv',
        'views/shariah_law.xml',
        'views/pos_order.xml',
        'views/purchase_order.xml',
        'views/donation.xml',
        'views/api_donation.xml',
        'views/hr_expense.xml',
        'views/account_analytic_account.xml',
        'wizards/transfer_wizard.xml',
    ],
    'auto_install': False,
    'application': True,
}