{
    'name': 'Shariah Law',
    'version': '1.0',
    'author': 'Syed Owais Noor',
    'website': 'https://bytesnode.com/',
    'license': 'LGPL-3',
    'category': 'BytesNode/Shariah Law',
    'depends': [
        'bn_analytic_account_customization',
        'bn_import_donation',
        'purchase',
        'hr_expense',
        'point_of_sale',
        'bn_microfinance',
        'bn_donation_in_kind',
        'bn_welfare',
    ],
    'data': [
        'data/ir_module_category.xml',
        'data/schedule_action.xml',
        'data/sequence.xml',
        'data/shariah_law_blocker.xml',
        'security/group.xml',
        'security/ir.model.access.csv',
        'views/shariah_daily_balance.xml',
        'views/shariah_transfer.xml',
        'views/shariah_law.xml',
        'views/shariah_law_config.xml',
        'views/shariah_law_sync_log.xml',
        'views/segment_transfer_rule.xml',
        'views/shariah_law_person.xml',
        'views/shariah_law_blocker.xml',
        'views/menu.xml',
        'views/pos_order.xml',
        'views/purchase_order.xml',
        'views/donation.xml',
        'views/api_donation.xml',
        'views/hr_expense.xml',
        'views/donation_in_kind.xml',
        'views/microfinance.xml',
        'views/welfare.xml',
        'views/account_analytic_account.xml',
        'wizards/transfer_wizard.xml',
    ],
    'auto_install': False,
    'application': True,
}