{
    'name': 'Profile Management',
    'version': '1.0',
    'summary': 'Layer above Contacts',
    'author': 'Syed Owais Noor',
    'website': 'https://bytesnode.com/',
    'license': 'LGPL-3',
    'category': 'BytesNode/Profile Management',
    'depends': [
        'bn_analytic_account_customization',
        'contacts',
    ],
    'data': [
        'data/sequence.xml',
        'data/server_action.xml',
        'data/res_partner_category.xml',
        'security/group.xml',
        'security/access_right.xml',
        'security/record_rule.xml',
        'security/ir.model.access.csv',
        'views/res_partner.xml',
        'views/res_partner_layer.xml',
        'views/product_template.xml',
        'views/product_product.xml',
        'wizards/confirm_search.xml',
        'wizards/record_search.xml',
        'wizards/microfinance_application_wizard.xml',
        'reports/profile_management_report.xml',
        'reports/microfinance_report.xml',
    ],
    'auto_install': False,
    'application': True,
}