{
    'name': 'Donation Box',
    'version': '1.0',
    'summary': 'Donation Box',
    'author': 'Shariq Mehdi',
    'website': 'https://bytesnode.com/',
    'license': 'LGPL-3',
    'category': 'TechnoCoderSol/DonationBox',
    # 'depends': ['base', 'mail', 'contacts', 'stock', 'sale_management', 'account'],
    'depends': ['bn_profile_management', 'mail', 'stock', 'sale_management', 'purchase', 'bn_master_setups'],
    'data': [
        'data/sequence.xml',
        'security/ir.model.access.csv',
        'security/groups.xml',
        'views/donation_box_registration.xml',
        'views/product.xml',
        # 'views/hr_employee.xml',
        'views/res_partner.xml',
        'views/donation_box_complain.xml',
        # 'views/donation_box_gl_account.xml',
        'menu/menu.xml',
        'views/view.xml',
    ],
    'auto_install': False,
    'application': True,
}