{
    'name': 'Donation Box',
    'version': '17.0.1.1.0',
    'author': 'Syed Owais Noor',
    'website': 'https://bytesnode.com/',
    'license': 'LGPL-3',
    'category': 'BytesNode/Donation Box',
    'depends': [
        'hr',
        'stock',
        'product',
        'bn_stock_location',
        'bn_pos_custom_action',
        'bn_profile_management',
        'bn_import_donation',
    ],
    'data': [
        'security/ir_module_category.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/server_action.xml',
        'data/sequence.xml',
        'data/hr_employee_category.xml',
        'views/donation_box_request.xml',
        'views/donation_box_registration_intallation.xml',
        'views/donation_box_complain_center.xml',
        'views/product_product.xml',
        'views/product_template.xml',
        'views/stock_lot.xml',
        'views/res_partner.xml',
        'views/donation_product_onhand.xml',
        'views/installation_category.xml',
        'views/res_company.xml',
        'views/stock_warehouse.xml',
        'reports/donation_box_report.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'auto_install': False,
    'application': True,
    'assets': {
        'point_of_sale._assets_pos': [
            'bn_donation_box/static/src/app/**/*',
            # 'bn_donation_box/static/src/screen/*',
        ],
    },
}